export const GET_PROFILES_OPTIONS_FETCHING = 'GET_PROFILES_OPTIONS_FETCHING';
export const GET_PROFILES_OPTIONS_FULFILLED = 'GET_PROFILES_OPTIONS_FULFILLED';
export const GET_PROFILES_OPTIONS_REJECTED = 'GET_PROFILES_OPTIONS_REJECTED';

export const GET_PROFILES_FETCHING = 'GET_PROFILES_FETCHING';
export const GET_PROFILES_FULFILLED = 'GET_PROFILES_FULFILLED';
export const GET_PROFILES_REJECTED = 'GET_PROFILES_REJECTED';

export const GET_PROFILE_BY_ID_FETCHING = 'GET_PROFILE_BY_ID_FETCHING';
export const GET_PROFILE_BY_ID_FULFILLED = 'GET_PROFILE_BY_ID_FULFILLED';
export const GET_PROFILE_BY_ID_REJECTED = 'GET_PROFILE_BY_ID_REJECTED';

export const ADD_PROFILE_FETCHING = 'ADD_PROFILE_FETCHING';
export const ADD_PROFILE_FULFILLED = 'ADD_PROFILE_FULFILLED';
export const ADD_PROFILE_REJECTED = 'ADD_PROFILE_REJECTED';

export const DELETE_PROFILE_FETCHING = 'DELETE_PROFILE_FETCHING';
export const DELETE_PROFILE_FULFILLED = 'DELETE_PROFILE_FULFILLED';
export const DELETE_PROFILE_REJECTED = 'DELETE_PROFILE_REJECTED';

export const UPDATE_PROFILE_FETCHING = 'UPDATE_PROFILE_FETCHING';
export const UPDATE_PROFILE_FULFILLED = 'UPDATE_PROFILE_FULFILLED';
export const UPDATE_PROFILE_REJECTED = 'UPDATE_PROFILE_REJECTED';

export const CLEAR_PROFILES_ERROR = 'CLEAR_PROFILES_ERROR';
export const CLEAN_SELECTED_ITEM = 'CLEAN_SELECTED_ITEM';
