export const GET_POSITIONS_FETCHING = 'GET_POSITIONS_FETCHING';
export const GET_POSITIONS_FULFILLED = 'GET_POSITIONS_FULFILLED';
export const GET_POSITIONS_REJECTED = 'GET_POSITIONS_REJECTED';

export const GET_POSITION_BY_ID_FETCHING = 'GET_POSITION_BY_ID_FETCHING';
export const GET_POSITION_BY_ID_FULFILLED = 'GET_POSITION_BY_ID_FULFILLED';
export const GET_POSITION_BY_ID_REJECTED = 'GET_POSITION_BY_ID_REJECTED';

export const ADD_POSITIONS_FETCHING = 'ADD_POSITIONS_FETCHING';
export const ADD_POSITIONS_FULFILLED = 'ADD_POSITIONS_FULFILLED';
export const ADD_POSITIONS_REJECTED = 'ADD_POSITIONS_REJECTED';

export const DELETE_POSITIONS_FETCHING = 'DELETE_POSITIONS_FETCHING';
export const DELETE_POSITIONS_FULFILLED = 'DELETE_POSITIONS_FULFILLED';
export const DELETE_POSITIONS_REJECTED = 'DELETE_POSITIONS_REJECTED';

export const UPDATE_POSITIONS_FETCHING = 'UPDATE_POSITIONS_FETCHING';
export const UPDATE_POSITIONS_FULFILLED = 'UPDATE_POSITIONS_FULFILLED';
export const UPDATE_POSITIONS_REJECTED = 'UPDATE_POSITIONS_REJECTED';

export const CLEAR_POSITIONS_ERROR = 'CLEAR_POSITIONS_ERROR';
export const CLEAR_SELECTED_POSITION = 'CLEAR_SELECTED_POSITION';
