export const GET_SESSIONS_FETCHING = 'GET_SESSIONS_FETCHING';
export const GET_SESSIONS_FULFILLED = 'GET_SESSIONS_FULFILLED';
export const GET_SESSIONS_REJECTED = 'GET_SESSIONS_REJECTED';

export const GET_SESSION_BY_ID_FETCHING = 'GET_SESSION_BY_ID_FETCHING';
export const GET_SESSION_BY_ID_FULFILLED = 'GET_SESSION_BY_ID_FULFILLED';
export const GET_SESSION_BY_ID_REJECTED = 'GET_SESSION_BY_ID_REJECTED';

export const GET_SESSIONS_OPTIONS_FETCHING = 'GET_SESSIONS_OPTIONS_FETCHING';
export const GET_SESSIONS_OPTIONS_FULFILLED = 'GET_SESSIONS_OPTIONS_FULFILLED';
export const GET_SESSIONS_OPTIONS_REJECTED = 'GET_SESSIONS_OPTIONS_REJECTED';

export const ADD_SESSIONS_FETCHING = 'ADD_SESSIONS_FETCHING';
export const ADD_SESSIONS_FULFILLED = 'ADD_SESSIONS_FULFILLED';
export const ADD_SESSIONS_REJECTED = 'ADD_SESSIONS_REJECTED';

export const DELETE_SESSIONS_FETCHING = 'DELETE_SESSIONS_FETCHING';
export const DELETE_SESSIONS_FULFILLED = 'DELETE_SESSIONS_FULFILLED';
export const DELETE_SESSIONS_REJECTED = 'DELETE_SESSIONS_REJECTED';

export const UPDATE_SESSIONS_FETCHING = 'UPDATE_SESSIONS_FETCHING';
export const UPDATE_SESSIONS_FULFILLED = 'UPDATE_SESSIONS_FULFILLED';
export const UPDATE_SESSIONS_REJECTED = 'UPDATE_SESSIONS_REJECTED';

export const CLEAR_SESSIONS_ERROR = 'CLEAR_SESSIONS_ERROR';
export const CLEAR_SELECTED_SESSION = 'CLEAR_SELECTED_SESSION';
