export const GET_POSTULANTS_FETCHING = 'GET_POSTULANTS_FETCHING';
export const GET_POSTULANTS_FULFILLED = 'GET_POSTULANTS_FULFILLED';
export const GET_POSTULANTS_REJECTED = 'GET_POSTULANTS_REJECTED';

export const GET_POSTULANTS_BY_ID_FETCHING = 'GET_POSTULANTS_BY_ID_FETCHING';
export const GET_POSTULANTS_BY_ID_FULFILLED = 'GET_POSTULANTS_BY_ID_FULFILLED';
export const GET_POSTULANTS_BY_ID_REJECTED = 'GET_POSTULANTS_BY_ID_REJECTED';

export const ADD_POSTULANTS_FETCHING = 'ADD_POSTULANTS_FETCHING';
export const ADD_POSTULANTS_FULFILLED = 'ADD_POSTULANTS_FULFILLED';
export const ADD_POSTULANTS_REJECTED = 'ADD_POSTULANTS_REJECTED';

export const DELETE_POSTULANTS_FETCHING = 'DELETE_POSTULANTS_FETCHING';
export const DELETE_POSTULANTS_FULFILLED = 'DELETE_POSTULANTS_FULFILLED';
export const DELETE_POSTULANTS_REJECTED = 'DELETE_POSTULANTS_REJECTED';

export const UPDATE_POSTULANTS_FETCHING = 'UPDATE_POSTULANTS_FETCHING';
export const UPDATE_POSTULANTS_FULFILLED = 'UPDATE_POSTULANTS_FULFILLED';
export const UPDATE_POSTULANTS_REJECTED = 'UPDATE_POSTULANTS_REJECTED';

export const CLEAR_POSTULANTS_ERROR = 'CLEAR_POSTULANTS_ERROR';

export const CLEAN_SELECTED_ITEM = 'CLEAN_SELECTED_ITEM';
