export const GET_ADMINS_FETCHING = 'GET_ADMINS_FETCHING';
export const GET_ADMINS_FULFILLED = 'GET_ADMINS_FULFILLED';
export const GET_ADMINS_REJECTED = 'GET_ADMINS_REJECTED';

export const GET_ADMIN_BY_ID_FETCHING = 'GET_ADMIN_BY_ID_FETCHING';
export const GET_ADMIN_BY_ID_FULFILLED = 'GET_ADMIN_BY_ID_FULFILLED';
export const GET_ADMIN_BY_ID_REJECTED = 'GET_ADMIN_BY_ID_REJECTED';

export const ADD_ADMINS_FETCHING = 'ADD_ADMINS_FETCHING';
export const ADD_ADMINS_FULFILLED = 'ADD_ADMINS_FULFILLED';
export const ADD_ADMINS_REJECTED = 'ADD_ADMINS_REJECTED';

export const DELETE_ADMINS_FETCHING = 'DELETE_ADMINS_FETCHING';
export const DELETE_ADMINS_FULFILLED = 'DELETE_ADMINS_FULFILLED';
export const DELETE_ADMINS_REJECTED = 'DELETE_ADMINS_REJECTED';

export const UPDATE_ADMINS_FETCHING = 'UPDATE_ADMINS_FETCHING';
export const UPDATE_ADMINS_FULFILLED = 'UPDATE_ADMINS_FULFILLED';
export const UPDATE_ADMINS_REJECTED = 'UPDATE_ADMINS_REJECTED';

export const CLEAN_ERROR = 'CLEAN_ERROR';

export const CLEAN_SELECTED_ITEM = 'CLEAN_SELECTED_ITEM';
