export const GET_INTERVIEWS_FETCHING = 'GET_INTERVIEWS_FETCHING';
export const GET_INTERVIEWS_FULFILLED = 'GET_INTERVIEWS_FULFILLED';
export const GET_INTERVIEWS_REJECTED = 'GET_INTERVIEWS_REJECTED';

export const GET_INTERVIEW_BY_ID_FETCHING = 'GET_INTERVIEW_BY_ID_FETCHING';
export const GET_INTERVIEW_BY_ID_FULFILLED = 'GET_INTERVIEW_BY_ID_FULFILLED';
export const GET_INTERVIEW_BY_ID_REJECTED = 'GET_INTERVIEW_BY_ID_REJECTED';

export const ADD_INTERVIEWS_FETCHING = 'ADD_INTERVIEWS_FETCHING';
export const ADD_INTERVIEWS_FULFILLED = 'ADD_INTERVIEWS_FULFILLED';
export const ADD_INTERVIEWS_REJECTED = 'ADD_INTERVIEWS_REJECTED';

export const DELETE_INTERVIEWS_FETCHING = 'DELETE_INTERVIEWS_FETCHING';
export const DELETE_INTERVIEWS_FULFILLED = 'DELETE_INTERVIEWS_FULFILLED';
export const DELETE_INTERVIEWS_REJECTED = 'DELETE_INTERVIEWS_REJECTED';

export const UPDATE_INTERVIEWS_FETCHING = 'UPDATE_INTERVIEWS_FETCHING';
export const UPDATE_INTERVIEWS_FULFILLED = 'UPDATE_INTERVIEWS_FULFILLED';
export const UPDATE_INTERVIEWS_REJECTED = 'UPDATE_INTERVIEWS_REJECTED';

export const CLEAR_INTERVIEWS_ERROR = 'CLEAR_INTERVIEWS_ERROR';
export const CLEAN_SELECTED_ITEM = 'CLEAN_SELECTED_ITEM';
