export const GET_PSYCHOLOGISTS_FETCHING = 'GET_PSYCHOLOGISTS_FETCHING';
export const GET_PSYCHOLOGISTS_FULFILLED = 'GET_PSYCHOLOGISTS_FULFILLED';
export const GET_PSYCHOLOGISTS_REJECTED = 'GET_PSYCHOLOGISTS_REJECTED';

export const GET_PSYCHOLOGIST_BY_ID_FETCHING = 'GET_PSYCHOLOGISTS_BY_ID_FETCHING';
export const GET_PSYCHOLOGIST_BY_ID_FULFILLED = 'GET_PSYCHOLOGISTS_BY_ID_FULFILLED';
export const GET_PSYCHOLOGIST_BY_ID_REJECTED = 'GET_PSYCHOLOGISTS_BY_ID_REJECTED';

export const ADD_PSYCHOLOGIST_FETCHING = 'ADD_PSYCHOLOGIST_FETCHING';
export const ADD_PSYCHOLOGIST_FULFILLED = 'ADD_PSYCHOLOGIST_FULFILLED';
export const ADD_PSYCHOLOGIST_REJECTED = 'ADD_PSYCHOLOGIST_REJECTED';

export const DELETE_PSYCHOLOGIST_FETCHING = 'DELETE_PSYCHOLOGIST_FETCHING';
export const DELETE_PSYCHOLOGIST_FULFILLED = 'DELETE_PSYCHOLOGIST_FULFILLED';
export const DELETE_PSYCHOLOGIST_REJECTED = 'DELETE_PSYCHOLOGIST_REJECTED';

export const UPDATE_PSYCHOLOGIST_FETCHING = 'UPDATE_PSYCHOLOGIST_FETCHING';
export const UPDATE_PSYCHOLOGIST_FULFILLED = 'UPDATE_PSYCHOLOGIST_FULFILLED';
export const UPDATE_PSYCHOLOGIST_REJECTED = 'UPDATE_PSYCHOLOGIST_REJECTED';

export const CLEAR_PSYCHOLOGIST_ERROR = 'CLEAR_PSYCHOLOGIST_ERROR';

export const CLEAN_SELECTED_ITEM = 'CLEAN_SELECTED_ITEM';
