export const GET_APPLICATIONS_FETCHING = 'GET_APPLICATIONS_FETCHING';
export const GET_APPLICATIONS_FULFILLED = 'GET_APPLICATIONS_FULFILLED';
export const GET_APPLICATIONS_REJECTED = 'GET_APPLICATIONS_REJECTED';

export const GET_APPLICATIONS_BY_ID_FETCHING = 'GET_APPLICATIONS_BY_ID_FETCHING';
export const GET_APPLICATIONS_BY_ID_FULFILLED = 'GET_APPLICATIONS_BY_ID_FULFILLED';
export const GET_APPLICATIONS_BY_ID_REJECTED = 'GET_APPLICATIONS_BY_ID_REJECTED';

export const GET_APPLICATIONS_OPTIONS_FETCHING = 'GET_APPLICATIONS_OPTIONS_FETCHING';
export const GET_APPLICATIONS_OPTIONS_FULFILLED = 'GET_APPLICATIONS_OPTIONS_FULFILLED';
export const GET_APPLICATIONS_OPTIONS_REJECTED = 'GET_APPLICATIONS_OPTIONS_REJECTED';

export const ADD_APPLICATIONS_FETCHING = 'ADD_APPLICATIONS_FETCHING';
export const ADD_APPLICATIONS_FULFILLED = 'ADD_APPLICATIONS_FULFILLED';
export const ADD_APPLICATIONS_REJECTED = 'ADD_APPLICATIONS_REJECTED';

export const DELETE_APPLICATIONS_FETCHING = 'DELETE_APPLICATIONS_FETCHING';
export const DELETE_APPLICATIONS_FULFILLED = 'DELETE_APPLICATIONS_FULFILLED';
export const DELETE_APPLICATIONS_REJECTED = 'DELETE_APPLICATIONS_REJECTED';

export const UPDATE_APPLICATIONS_FETCHING = 'UPDATE_APPLICATIONS_FETCHING';
export const UPDATE_APPLICATIONS_FULFILLED = 'UPDATE_APPLICATIONS_FULFILLED';
export const UPDATE_APPLICATIONS_REJECTED = 'UPDATE_APPLICATIONS_REJECTED';

export const CLEAR_APPLICATIONS_ERROR = 'CLEAR_APPLICATIONS_ERROR';
export const CLEAR_SELECTED_APPLICATIONS = 'CLEAR_SELECTED_APPLICATIONS';
