export const GET_CLIENTS_FETCHING = 'GET_CLIENTS_FETCHING';
export const GET_CLIENTS_FULFILLED = 'GET_CLIENTS_FULFILLED';
export const GET_CLIENTS_REJECTED = 'GET_CLIENTS_REJECTED';

export const GET_CLIENTS_BY_ID_FETCHING = 'GET_CLIENT_BY_ID_FETCHING';
export const GET_CLIENTS_BY_ID_FULFILLED = 'GET_CLIENT_BY_ID_FULFILLED';
export const GET_CLIENTS_BY_ID_REJECTED = 'GET_CLIENT_BY_ID_REJECTED';

export const ADD_CLIENTS_FETCHING = 'ADD_CLIENTS_FETCHING';
export const ADD_CLIENTS_FULFILLED = 'ADD_CLIENTS_FULFILLED';
export const ADD_CLIENTS_REJECTED = 'ADD_CLIENTS_REJECTED';

export const DELETE_CLIENTS_FETCHING = 'DELETE_CLIENTS_FETCHING';
export const DELETE_CLIENTS_FULFILLED = 'DELETE_CLIENTS_FULFILLED';
export const DELETE_CLIENTS_REJECTED = 'DELETE_CLIENTS_REJECTED';

export const UPDATE_CLIENTS_FETCHING = 'UPDATE_CLIENTS_FETCHING';
export const UPDATE_CLIENTS_FULFILLED = 'UPDATE_CLIENTS_FULFILLED';
export const UPDATE_CLIENTS_REJECTED = 'UPDATE_CLIENTS_REJECTED';

export const CLEAR_CLIENTS_ERROR = 'CLEAR_CLIENTS_ERROR';

export const CLEAN_SELECTED_ITEM = 'CLEAN_SELECTED_ITEM';
